### ISSUE TITLE
[feature] WearOS version

### ISSUE THREAD

**Issue by Kaaveh** [Kaaveh/ComposeNews#176]

**Comment by rezazarchi** [comment]
I think we can implement WearOS application using Jetpack Compose. However, we also need to consider the Tiles feature, which is a way to display glanceable information on the watch home (seems like widgets in mobiles). Tiles cannot be implemented with Jetpack Compose, but they can be implemented with Jetpack Wear ProtoLayout, which is a library that provides common layouts for Wear OS, and also there are more limitations and complications in the implementation of this section to have maximum efficiency and minimum consumption of resources and battery energy.
Therefore, I think, in order to more consistency and integration with the rest of the project code, we first focus on developing the main application with Jetpack Compose, and then, we can think about adding Tile with ProtoLayout or maybe other ways in the future.

**Comment by Kaaveh** [comment]
That's great! Do what you think is best! 🙌🏻
